services:
  kafka-tls:
    image: confluentinc/cp-kafka:8.2.0
    container_name: dotnet-kafka-adapter-kafka-tls
    hostname: kafka-tls
    ports:
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,SSL_HOST:SSL"
      KAFKA_LISTENERS: "PLAINTEXT://kafka-tls:29092,CONTROLLER://kafka-tls:29093,SSL_HOST://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-tls:29092,SSL_HOST://localhost:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-tls:29093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_KEYSTORE_TYPE: "PKCS12"
      KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets/server.keystore.p12"
      KAFKA_SSL_KEYSTORE_PASSWORD: "changeit"
      KAFKA_SSL_KEY_PASSWORD: "changeit"
      KAFKA_SSL_TRUSTSTORE_TYPE: "PKCS12"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets/server.truststore.p12"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "changeit"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2QV"
    volumes:
      - ./dev/kafka-tls/certs:/etc/kafka/secrets:ro
      - kafka_tls_data:/var/lib/kafka/data

volumes:
  kafka_tls_data:
